// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Entities;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240122132921_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Models.ItemMaster", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManageItemBy")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumInventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumInventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PurchasedItem")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SalesItem")
                        .HasColumnType("bit");

                    b.Property<bool>("StockItem")
                        .HasColumnType("bit");

                    b.HasKey("ItemCode");

                    b.ToTable("ItemMaster", (string)null);

                    b.HasData(
                        new
                        {
                            ItemCode = "e0d16ac6-1e4b-45f7-8e87-1",
                            Active = true,
                            Barcode = "070590708898824485667995070969",
                            DateCreated = new DateTime(2024, 1, 22, 14, 29, 20, 793, DateTimeKind.Local).AddTicks(8688),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
                            ImagePath = "374ad050-7773-4f42-86d2-fbb66273f13b.png",
                            ManageItemBy = 0,
                            MaximumInventory = 100m,
                            MinimumInventory = 0m,
                            PurchasedItem = false,
                            SalesItem = false,
                            StockItem = true
                        },
                        new
                        {
                            ItemCode = "d18912c0-ac67-470c-a83f-0",
                            Active = true,
                            Barcode = "070590708898824485667995070969",
                            DateCreated = new DateTime(2024, 1, 22, 14, 29, 20, 793, DateTimeKind.Local).AddTicks(8813),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
                            ImagePath = "58108b9a-e114-4d02-9967-f8a00e42ef59.png",
                            ManageItemBy = 0,
                            MaximumInventory = 100m,
                            MinimumInventory = 0m,
                            PurchasedItem = false,
                            SalesItem = false,
                            StockItem = true
                        },
                        new
                        {
                            ItemCode = "c8413b69-8f44-49f7-a788-f",
                            Active = true,
                            Barcode = "070590708898824485667995070969",
                            CustomerDescription = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
                            DateCreated = new DateTime(2024, 1, 22, 14, 29, 20, 793, DateTimeKind.Local).AddTicks(8822),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.",
                            ImagePath = "9e9ef54a-f995-4da1-95ee-3456414d28fb.png",
                            ManageItemBy = 1,
                            MaximumInventory = 100m,
                            MinimumInventory = 0m,
                            PurchasedItem = false,
                            Remarks = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.",
                            SalesItem = false,
                            StockItem = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
